build_image:
  stage: build
  script:
    - hostname
    - uptime
    - uname -a
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/szabgab/gl-try:latest .
    - docker push $CI_REGISTRY/szabgab/gl-try:latest
  tags:
    - shell-runner

use_image:
  stage: test
  image: $CI_REGISTRY/szabgab/gl-try:latest
  script:
    - hostname
    - uptime
    - uname -a
    - pwd
    - ls -l
    - ls -l /opt
    - cat /opt/date.txt
    - date

