---
- hosts: all
  gather_facts : no
  vars:
     kibana: kibana-7.11.2-x86_64.rpm
     project_root: /root
  tasks:
    - get_url:
        url="https://artifacts.elastic.co/downloads/kibana/{{kibana}}"
        dest="{{project_root}}/{{kibana}}"
    - name: Check if Kibana is installed
      command: rpm -q kibana
      ignore_errors: True
      register: rpm_check

    - name: Install
      ansible.builtin.shell: rpm -vi {{kibana}}
      when: rpm_check.rc != 0

    - name: Enable and Start
      ansible.builtin.service:
        name: kibana
        state: started
        enabled: yes

    - name: Copy configuration file
      copy:
        src: ../files/etc/kibana/kibana.yml
        dest: /etc/kibana/kibana.yml


#    - name: Server host
#      lineinfile:
#        destfile: /etc/kibana/kibana.yml
#        regexp: 'server.host:'
#        line: 'server.host: ["localhost"]'
#
#    - name: Defining Elasticsearch URL
#      lineinfile:
#        destfile: /etc/kibana/kibana.yml
#        regexp: 'elasticsearch.hosts:'
#        line: 'elasticsearch.hosts: ["http://localhost:9200"]'

    - name: Restart
      ansible.builtin.service:
        name: kibana
        state: restarted


