---
- hosts: all
  gather_facts : no
  vars:
     project_root: /root
  tasks:
    - name: Enable epel
      yum:
        name: epel-release
        state: present
    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Enable and Start
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: Nginx config file
      copy:
        src: ../nginx.conf
        dest: /etc/nginx/nginx.conf

    - name: Nginx config file
      copy:
        src: ../nginx-elk.conf
        dest: /etc/nginx/conf.d/nginx-elk.conf

    - name: Nginx users file
      copy:
        src: ../.htpasswd
        dest: /etc/nginx/.htpasswd

    - name: Restart
      ansible.builtin.service:
        name: nginx 
        state: restarted




